### ISSUE TITLE
Dev workflow

### ISSUE THREAD

**Issue by ankitbko** [AI4Bharat/INCLUDE-teams-expt#2]
@pratyush108 Will you be adding us to this repo as contributor or should we fork this repo individually to do development?
https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/adding-outside-collaborators-to-repositories-in-your-organization

cc: @drmcghee

**Comment by GokulNC** [comment]
You already seem to have maintainer access, so closing this issue :)
